test: check auto test from last versions

diff --git a/.github/workflows/upgrade-test.yaml b/.github/workflows/upgrade-test.yaml
--- a/.github/workflows/upgrade-test.yaml
+++ b/.github/workflows/upgrade-test.yaml
@@ -21,6 +21,10 @@ on:
   issue_comment:
     types:
       - created
+
+  push:
+    branches:
+      - upgradeTestPipeline
   
   
 
@@ -32,37 +36,37 @@ jobs:
       (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test'))
     steps:
       - name: Setup Docker Buildx
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         uses: docker/setup-buildx-action@f7ce87c1d6bead3e36075b2ce75da1f6cc28aaca # v3.9.0
         with:
             version: v0.15.1
             install: true
       - name: Checkout code
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
           submodules: true
       - name: Fetch History
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         run: git fetch --prune --unshallow
 
       - name: Set up Go
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
         with:
           go-version: '1.21'
 
       - name: Vendor Dependencies
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         run: make vendor vendor.check
 
       - name: Set up Version
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         run: |
           echo "BUILD_IMAGE_VERSION=draft-${{ github.event.pull_request.number }}" >> $GITHUB_ENV
           echo "version is $BUILD_IMAGE_VERSION"
       - name: Build Images
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         run: make build VERSION=$BUILD_IMAGE_VERSION 
         env:
           # We're using docker buildx, which doesn't actually load the images it
@@ -72,14 +76,14 @@ jobs:
           BUILD_REGISTRY: ${{ vars.REGISTRY_URL }}
 
       - name: Login to Container Registry
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
         with:
           registry: ${{ vars.REGISTRY_URL }}
           username: ${{ github.actor }}
           password: ${{ secrets.GITHUB_TOKEN }}
       - name: Publish Artifacts to DockerHub
-        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test')
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
         run: make publish BRANCH_NAME=${GITHUB_REF##*/} VERSION=$BUILD_IMAGE_VERSION
         env:
           DOCKER_REGISTRY: ${{ vars.REGISTRY_URL }}
@@ -120,35 +124,34 @@ jobs:
           sudo chmod +x /usr/bin/yq
 
           echo "All tools installed successfully."
-
-      - name: Extract params
-        run: |
-          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
-            echo "to_test_source=${{ github.event.inputs.source }}" >> $GITHUB_ENV
-            echo "to_test_target=${{ github.event.inputs.target }}" >> $GITHUB_ENV
-          elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
-            COMMENT_BODY="${{ github.event.comment.body }}"
-            if [[ "$COMMENT_BODY" =~ /upgrade-test ]]; then
-              VERSION=$(echo "$COMMENT_BODY" | awk -F'source=' '{print $2}' | awk '{print $1}')
-              if [[ -n "$VERSION" ]]; then
-                echo "Extracted version: $VERSION"
-                echo "to_test_source=$VERSION" >> $GITHUB_ENV
-                echo "to_test_source=$to_test_source"
-              else
-                echo "Error: 'source' parameter is missing or invalid." >&2
-                exit 1
-              fi
-              echo "to_test_target=$BUILD_IMAGE_VERSION" >> $GITHUB_ENV
-              echo "to_test_target=$to_test_target"
-            else
-              echo "Comment does not start with '/upgrade-test'." 
-            fi
-          fi
       - name: Run upgrade test
+        if: github.event_name == 'workflow_dispatch' 
         run: |
           cd provider-upgrade-test
           echo "Running upgrade test..."
           REGISTRY=ghcr.io/sap/crossplane-provider-btp/crossplane/provider-btp && ./provider-test.sh upgrade-test --source "${REGISTRY}:${to_test_source}" --target ${REGISTRY}:${to_test_target} --provider provider-btp   --initialize providers/provider-btp/scripts/initialize.sh --cleanup  providers/provider-btp/scripts/cleanup.sh
+        env: 
+          CLIENT_ID: ${{ secrets.UPGRADE_TEST_CLIENT_ID }}
+          CLIENT_SECRET: ${{ secrets.UPGRADE_TEST_CLIENT_SECRET }}
+          TECH_USER_PASSWORD: ${{ secrets.UPGRADE_TEST_TECH_USER_PW }}
+
+      - name: Run upgrade test from the last versions
+        if: github.event_name == 'issue_comment' && contains(github.event.comment.body, '/upgrade-test') && true
+        run: |
+          cd provider-upgrade-test
+          echo "Running upgrade test..."
+          latest_versions=$(ls -d providers/provider-btp/v* 2>/dev/null | sort -V | tail -n 3 | xargs -n 1 basename)
+
+          if [[ -z "$latest_versions" ]]; then
+            echo "Error: No versions found in providers/provider-btp." >&2
+            exit 1
+          fi
+          echo "Latest three versions supports upgrade test are: $latest_versions"
+          for source_version in $latest_versions; do
+            echo "Running upgrade test from version: $source_version"
+            REGISTRY=ghcr.io/sap/crossplane-provider-btp/crossplane/provider-btp && ./provider-test.sh upgrade-test --source "${REGISTRY}:${source_version}" --target ${REGISTRY}:${BUILD_IMAGE_VERSION} --provider provider-btp   --initialize providers/provider-btp/scripts/initialize.sh --cleanup  providers/provider-btp/scripts/cleanup.sh
+            echo "Upgrade test finished for version: $source_version"
+          done
         env: 
           CLIENT_ID: ${{ secrets.UPGRADE_TEST_CLIENT_ID }}
           CLIENT_SECRET: ${{ secrets.UPGRADE_TEST_CLIENT_SECRET }}
