test: secure input commet

diff --git a/.github/workflows/upgrade-test.yaml b/.github/workflows/upgrade-test.yaml
--- a/.github/workflows/upgrade-test.yaml
+++ b/.github/workflows/upgrade-test.yaml
@@ -127,23 +127,22 @@ jobs:
             echo "to_test_source=${{ github.event.inputs.source }}" >> $GITHUB_ENV
             echo "to_test_target=${{ github.event.inputs.target }}" >> $GITHUB_ENV
           elif [[ "${{ github.event_name }}" == "issue_comment" ]]; then
-            echo "COMMENT_BODY=${{ github.event.comment.body }}" >> $GITHUB_ENV
-            COMMENT_BODY="$COMMENT_BODY"
-            if [[ "$COMMENT_BODY" =~ /upgrade-test ]]; then
-              if [[ "$COMMENT_BODY" =~ source=([^\ ]+) ]]; then
-                  to_test_source="${BASH_REMATCH[1]}"
-                  # Validate and sanitize to_test_source
-                  if [[ "$to_test_source" =~ ^[a-zA-Z0-9._-]+$ ]]; then
-                    echo "to_test_source=$to_test_source" >> $GITHUB_ENV
-                    echo "to_test_source=$to_test_source"
-                  else
-                    echo "Invalid source value: $to_test_source" >&2
-                    exit 1
-                  fi
+            COMMENT_BODY="${{ github.event.comment.body }}"
+            COMMENT_BODY=$(echo "$COMMENT_BODY" | tr -d '\r\n')
+            if [[ "$COMMENT_BODY" =~ ^/upgrade-test\ source= ]]; then
+              VERSION=$(echo "$COMMENT_BODY" | awk -F'source=' '{print $2}' | awk '{print $1}')
+              if [[ -n "$VERSION" ]]; then
+                echo "Extracted version: $VERSION"
+                echo "to_test_source=$VERSION" >> $GITHUB_ENV
+                echo "to_test_source=$to_test_source"
+              else
+                echo "Error: 'source' parameter is missing or invalid." >&2
+                exit 1
               fi
-              to_test_target="${BUILD_IMAGE_VERSION}"
-              echo "to_test_target=$to_test_target" >> $GITHUB_ENV
+              echo "to_test_target=$BUILD_IMAGE_VERSION" >> $GITHUB_ENV
               echo "to_test_target=$to_test_target"
+            else
+              echo "Comment does not start with '/upgrade-test'." 
             fi
           fi
       - name: Run upgrade test
